# 11ty build
[build]
  publish = "_site"
  command = "eleventy"

# Security policy
[[headers]]
for = "/*"

[headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Cross-Origin-Resource-Policy = "same-site"
  Cross-Origin-Embedder-Policy = "same-origin"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Content-Security-Policy = "upgrade-insecure-requests"
  Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"

# secure browser
[[redirects]]
from = "https://.digitaldesigners.netlify.app"
to = "https://digitaldesigners.ca"
status = 301
force = true

# page routes
[[redirects]]
from = "/blog"
to = "/studies"
status = 301
force = true

[[redirects]]
from = "/post"
to = "/studies"
status = 301
force = true

[[redirects]]
from = "/publish"
to = "/studies"
status = 301
force = true

[[redirects]]
from = "/article"
to = "/studies"
status = 301
force = true

[[redirects]]
from = "/feed"
to = "/feed.xml"
status = 301
force = true

[[redirects]]
from = "/rss"
to = "/rss.xml"
status = 301
force = true

[[redirects]]
from = "/sitemap"
to = "/sitemap.xml"
status = 301
force = true

[[redirects]]
from = "/help"
to = "/help.html"
status = 301
force = true

[[redirects]]
from = "/logo"
to = "/assets/social-image.jpg"
status = 301
force = true

[[redirects]]
from = "/favicon"
to = "/favicon.ico"
status = 301
force = true

# social media 
[[redirects]]
from = "/twitter"
to = "https://twitter.com/ddesignersca"
status = 301
force = true

[[redirects]]
from = "/instagram"
to = "https://instagram.com/digitaldesignersca/"
status = 301
force = true

[[redirects]]
from = "/facebook"
to = "https://facebook.com/digitaldesignersca"
status = 301
force = true

[[redirects]]
from = "/linkedin"
to = "https://linkedin.com/company/digitaldesignersca"
status = 301
force = true

# netlify redirect
[[redirects]]
  from = "https://digitaldesigners.netlify.app"
  to = "https://digitaldesigners.ca"
  status = 301
  force = true

# web analytics
[[redirects]]
  from = "/g/collect"
  to = "https://google-analytics.com/g/collect"
  status = 200
